#!/bin/bash
set -e

echo "Setting up local.properties..."

# Check if ANDROID_SDK_ROOT is set
if [ -z "$ANDROID_SDK_ROOT" ]; then
    echo "Warning: ANDROID_SDK_ROOT environment variable is not set"
    echo "Please set it to your Android SDK installation directory"
    echo "Example: export ANDROID_SDK_ROOT=~/Library/Android/sdk"
    exit 1
fi

# Create local.properties file
cat > local.properties << EOF
# This file was automatically generated by setup-local-properties.sh
# Do not commit this file to version control
sdk.dir=$ANDROID_SDK_ROOT
EOF

echo "Created local.properties with sdk.dir=$ANDROID_SDK_ROOT"